// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Indexer.Service")>]
[<assembly: AssemblyProductAttribute("Indexer")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2021-02-10T00:00:00.0000000+01:00")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyInformationalVersionAttribute("0.0.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","alpha")>]
[<assembly: AssemblyMetadataAttribute("GitHash","a626c7b62aa0dcf87e8ea7b844c1e674b5e9abdd")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Indexer.Service"
    let [<Literal>] AssemblyProduct = "Indexer"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2021-02-10T00:00:00.0000000+01:00"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyInformationalVersion = "0.0.1"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "alpha"
    let [<Literal>] AssemblyMetadata_GitHash = "a626c7b62aa0dcf87e8ea7b844c1e674b5e9abdd"
