// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Signer.Test")>]
[<assembly: AssemblyProductAttribute("Signer")>]
[<assembly: AssemblyVersionAttribute("0.0.4")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2021-02-10T00:00:00.0000000+01:00")>]
[<assembly: AssemblyFileVersionAttribute("0.0.4")>]
[<assembly: AssemblyInformationalVersionAttribute("0.0.4")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","678dc9e447721c6b4567c6a25babdff4555a225c")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Signer.Test"
    let [<Literal>] AssemblyProduct = "Signer"
    let [<Literal>] AssemblyVersion = "0.0.4"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2021-02-10T00:00:00.0000000+01:00"
    let [<Literal>] AssemblyFileVersion = "0.0.4"
    let [<Literal>] AssemblyInformationalVersion = "0.0.4"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "678dc9e447721c6b4567c6a25babdff4555a225c"
