// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Signer.Test")>]
[<assembly: AssemblyProductAttribute("Signer")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2021-02-10T00:00:00.0000000+01:00")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyInformationalVersionAttribute("0.0.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","c184478102ecd727824e9e6a0cf3f77237f77ee7")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Signer.Test"
    let [<Literal>] AssemblyProduct = "Signer"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2021-02-10T00:00:00.0000000+01:00"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyInformationalVersion = "0.0.1"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "c184478102ecd727824e9e6a0cf3f77237f77ee7"
